### ISSUE TITLE
fzr and fzc

### ISSUE THREAD

**Issue by Maverick283** [supersim65/exporting-google-sheets-pdfs#1]
Just writing as I used this to create a PDF but I needed frozen rows and columns to repeat themselves. 

Turns out, fzr and fzc does exactly that. When set to true, fzr and fzc make frozen rows and columns repeat on each page respectively.

Also, if you want to extend this guide, it is also possible to set a selection using the parameters 'c1', 'r1', 'c2' and 'r2' to specify, in integers starting from 0, the column number and row number from where to start (c1 and r1) the selection to where to end the selection (c2 and r2).

**Comment by simonsprofile** [comment]
> Just writing as I used this to create a PDF but I needed frozen rows and columns to repeat themselves.
> 
> Turns out, fzr and fzc does exactly that. When set to true, fzr and fzc make frozen rows and columns repeat on each page respectively.
> 
> Also, if you want to extend this guide, it is also possible to set a selection using the parameters 'c1', 'r1', 'c2' and 'r2' to specify, in integers starting from 0, the column number and row number from where to start (c1 and r1) the selection to where to end the selection (c2 and r2).

Thanks Maverick. I went to update the document now, but I had trouble when testing those parameters in action:
- `fzr` worked with 0 as expected, 1 did not freeze a row, and anything greater than 1 produced an error.
- `r1`, `c1`, `r2`, `c2` did not work for me.

Do you have an example of a working URL I could compare against?

**Comment by Maverick283** [comment]
Hi, thanks for updating! Always good to see!

It's not that the parameters create a frozen row/column, it just specifies that the (existing) frozen row/column should be shown on every page. 

To test it, create a sheet with a frozen row and set the fzr parameter to 1. The frozen row will appear on the top of each page. 

Sorry for not providing an example, I promised the batter half a time off the laptop and it is freakishly hard to do this on a phone.

**Comment by simonsprofile** [comment]
That's great, I understand now. The r1c1 problem I was having was because I made a typo too, so all updated. Thanks for letting me know!
