### ISSUE TITLE
Fit to Width/Height/Page

### ISSUE THREAD

**Issue by ItsJustSomeDude** [supersim65/exporting-google-sheets-pdfs#2]
I found the route parameters for Fit to Height/Fit to Page: `scale`.  It takes an Integer, and the options seem to map to the dropdown on the print dialog.  Setting scale to 3 does Fit to Height, which is all I needed for my project.  I haven't tested what happens if both `fitw` and `scale` are included though, nor do I know how to set or configure the Custom Scale.

**Comment by simonsprofile** [comment]
Thanks @ItsJustSomeDude. I have tested 1, 2 and 4 and they do map as you expected. Document updated.
